/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TicketX } from "./TicketX";
export * as factories from "./factories";
export { TicketX__factory } from "./factories/TicketX__factory";
